### PR TITLE
Added basic setup.py to enable installing as a python package.

### PR DESCRIPTION
**Pull request by edlanglois**
Install with `pip install -e .` from lczero_tools directory.

### CODE REVIEW

**Review by trevor-graffa — COMMENTED** [review]
I'm not sure what dask is (other than what I quickly found on Google)... If the other pull requests by you show that this is something we really want here, I'll merge this as is.

**Comment by edlanglois** [comment]
My bad, there used to be `from distributed.worker import weight` in `_leela_torch_net.py` and I came across [Dask.distributed](https://distributed.readthedocs.io/en/latest/) when searching for it and thought `distributed` was provided by `dask` (I see now that it's a separate package). Either way, that line is gone so I'll remove the dependency.

**Comment by trevor-graffa** [comment]
Gotcha. So it was my fault! The "distributed.worker" line either was automatically added by one of my IDEs, or I accidentally copied it from leela-chess (I borrowed code that sets up training pipeline so that I could use their "tfprocess" module to ensure this works with tensorflow -- this was only meant to be a temporary hack until I actually get around to reconstructing the tf net outside of tfrpocess).

**Comment by trevor-graffa** [comment]
Thanks for the PRs!

**Pull request merged**
